//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWork.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Silverlight", ConfigurationName="ServiceReference1.IEchoDuplexService", CallbackContract=typeof(MyWork.ServiceReference1.IEchoDuplexServiceCallback))]
    public interface IEchoDuplexService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Silverlight/IEchoDuplexService/Echo", ReplyAction="Silverlight/IEchoDuplexService/EchoResponse")]
        string Echo([System.ServiceModel.MessageParameterAttribute(Name="Echo")] string Echo1);
        
        [System.ServiceModel.OperationContractAttribute(Action="Silverlight/IEchoDuplexService/Register", ReplyAction="Silverlight/IEchoDuplexService/RegisterResponse")]
        bool Register(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="Silverlight/IEchoDuplexService/UnRegister", ReplyAction="Silverlight/IEchoDuplexService/UnRegisterResponse")]
        bool UnRegister(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoDuplexServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Silverlight/IEchoDuplexService/Receive")]
        void Receive(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoDuplexServiceChannel : MyWork.ServiceReference1.IEchoDuplexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoDuplexServiceClient : System.ServiceModel.DuplexClientBase<MyWork.ServiceReference1.IEchoDuplexService>, MyWork.ServiceReference1.IEchoDuplexService {
        
        public EchoDuplexServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public EchoDuplexServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public EchoDuplexServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EchoDuplexServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EchoDuplexServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string Echo(string Echo1) {
            return base.Channel.Echo(Echo1);
        }
        
        public bool Register(string id) {
            return base.Channel.Register(id);
        }
        
        public bool UnRegister(string id) {
            return base.Channel.UnRegister(id);
        }
    }
}
